// Generated by ReScript, PLEASE EDIT WITH CARE


var Check = {};

var ChevronLeft = {};

var ChevronRight = {};

var ThumbsUp = {};

var Mail = {};

var Download = {};

var Home = {};

var User = {};

var Settings = {};

var Shield = {};

var Zap = {};

var Users = {};

var BarChart = {};

export {
  Check ,
  ChevronLeft ,
  ChevronRight ,
  ThumbsUp ,
  Mail ,
  Download ,
  Home ,
  User ,
  Settings ,
  Shield ,
  Zap ,
  Users ,
  BarChart ,
}
/* No side effect */
