// Generated by ReScript, PLEASE EDIT WITH CARE


function createMultiSelectItem(id, text, disabledOpt) {
  var disabled = disabledOpt !== undefined ? disabledOpt : false;
  return {
          id: id,
          text: text,
          disabled: disabled,
          type_: "MULTI_SELECT",
          isMultiSelect: true
        };
}

export {
  createMultiSelectItem ,
}
/* No side effect */
