// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as LucideReact from "lucide-react";
import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function AccordionDemo$AccordionDemo(props) {
  var match = React.useState(function () {
        return "item-1";
      });
  var setExpandedValue = match[1];
  var expandedValue = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Accordion Demo",
                      className: "text-2xl font-bold mb-6 mt-12"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Basic Accordion",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs(DesignSystem.Accordion, {
                              children: [
                                JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                      value: "item-1",
                                      title: "Accordion Item 1",
                                      children: JsxRuntime.jsx("div", {
                                            children: "Basic accordion content"
                                          })
                                    }),
                                JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                      value: "item-2",
                                      title: "Accordion Item 2",
                                      children: JsxRuntime.jsx("div", {
                                            children: "Another accordion item"
                                          })
                                    })
                              ]
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Accordion Types",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "Border Type",
                                              className: "mb-2"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.Accordion, {
                                              children: JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                                    value: "border-1",
                                                    title: "Border Style Item",
                                                    children: JsxRuntime.jsx("div", {
                                                          children: "Content with border style"
                                                        })
                                                  }),
                                              accordionType: "border",
                                              defaultValue: "item-1"
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "No Border Type",
                                              className: "mb-2"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.Accordion, {
                                              children: JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                                    value: "noborder-1",
                                                    title: "No Border Style Item",
                                                    children: JsxRuntime.jsx("div", {
                                                          children: "Content without border"
                                                        })
                                                  }),
                                              accordionType: "noborder"
                                            })
                                      ]
                                    })
                              ],
                              className: "flex flex-col gap-6"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Accordion with Subtext",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsx(DesignSystem.Accordion, {
                              children: JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                    value: "subtext-1",
                                    title: "Item with Subtext",
                                    subtext: "This is additional information about this item",
                                    children: JsxRuntime.jsx("div", {
                                          children: "Content with subtext"
                                        })
                                  })
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Accordion with Slots",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs(DesignSystem.Accordion, {
                              children: [
                                JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                      value: "slots-1",
                                      title: "Item with Left Slot",
                                      leftSlot: Caml_option.some(JsxRuntime.jsx(LucideReact.Check, {
                                                size: 16,
                                                color: "green"
                                              })),
                                      children: JsxRuntime.jsx("div", {
                                            children: "Content with left slot"
                                          })
                                    }),
                                JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                      value: "slots-2",
                                      title: "Item with Right Slot",
                                      rightSlot: Caml_option.some(JsxRuntime.jsx(LucideReact.Tag, {})),
                                      children: JsxRuntime.jsx("div", {
                                            children: "Content with right slot"
                                          })
                                    })
                              ]
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Controlled Accordion",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs(DesignSystem.Accordion, {
                              children: [
                                JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                      value: "controlled-1",
                                      title: "Controlled Item 1",
                                      children: JsxRuntime.jsx("div", {
                                            children: "First controlled item"
                                          })
                                    }),
                                JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                      value: "controlled-2",
                                      title: "Controlled Item 2",
                                      children: JsxRuntime.jsx("div", {
                                            children: "Second controlled item"
                                          })
                                    })
                              ],
                              value: expandedValue,
                              onValueChange: (function (value) {
                                  setExpandedValue(function (param) {
                                        return value;
                                      });
                                })
                            }),
                        JsxRuntime.jsx("div", {
                              children: "Currently expanded: " + expandedValue,
                              className: "mt-2 text-sm text-gray-600"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Disabled Accordion Items",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs(DesignSystem.Accordion, {
                              children: [
                                JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                      value: "disabled-1",
                                      title: "Disabled Item",
                                      children: JsxRuntime.jsx("div", {
                                            children: "This content won't be visible"
                                          }),
                                      isDisabled: true
                                    }),
                                JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                      value: "disabled-2",
                                      title: "Enabled Item",
                                      children: JsxRuntime.jsx("div", {
                                            children: "This content is accessible"
                                          })
                                    })
                              ]
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Chevron Positions",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "Left Chevron",
                                              className: "mb-2"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.Accordion, {
                                              children: JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                                    value: "chevron-left",
                                                    title: "Left Chevron Item",
                                                    children: JsxRuntime.jsx("div", {
                                                          children: "Content with left chevron"
                                                        }),
                                                    chevronPosition: "left"
                                                  })
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "Right Chevron",
                                              className: "mb-2"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.Accordion, {
                                              children: JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                                    value: "chevron-right",
                                                    title: "Right Chevron Item",
                                                    children: JsxRuntime.jsx("div", {
                                                          children: "Content with right chevron"
                                                        }),
                                                    chevronPosition: "right"
                                                  })
                                            })
                                      ]
                                    })
                              ],
                              className: "flex flex-col gap-6"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Collapsible Accordion",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs(DesignSystem.Accordion, {
                              children: [
                                JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                      value: "collapsible-1",
                                      title: "Collapsible Item 1",
                                      children: JsxRuntime.jsx("div", {
                                            children: "First collapsible item"
                                          })
                                    }),
                                JsxRuntime.jsx(DesignSystem.AccordionItem, {
                                      value: "collapsible-2",
                                      title: "Collapsible Item 2",
                                      children: JsxRuntime.jsx("div", {
                                            children: "Second collapsible item"
                                          })
                                    })
                              ],
                              isCollapsible: true
                            })
                      ],
                      className: "mb-8"
                    })
              ]
            });
}

var AccordionDemo = {
  make: AccordionDemo$AccordionDemo
};

export {
  AccordionDemo ,
}
/* react Not a pure module */
