// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function AvatarDemo$AvatarDemo(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Avatar Demo",
                      className: "text-2xl font-bold mb-6 mt-12"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Avatar Sizes",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              fallback: "SM",
                                              size: "sm"
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "Small",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              fallback: "RE",
                                              size: "regular"
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "Regular",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              fallback: "MD",
                                              size: "md"
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "Medium",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              fallback: "LG",
                                              size: "lg"
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "Large",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              fallback: "XL",
                                              size: "xl"
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "Extra Large",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    })
                              ],
                              className: "flex items-center gap-6"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Avatar Shapes",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              fallback: "CR",
                                              size: "lg",
                                              shape: "circular"
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "Circular",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              fallback: "RO",
                                              size: "lg",
                                              shape: "rounded"
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "Rounded",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    })
                              ],
                              className: "flex items-center gap-8"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Avatar with Image vs Fallback",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              src: "https://i.pravatar.cc/150?img=1",
                                              alt: "User avatar",
                                              size: "lg"
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "With Image",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              fallback: "JD",
                                              size: "lg"
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "With Fallback",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    })
                              ],
                              className: "flex items-center gap-8"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Online Status",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              src: "https://i.pravatar.cc/150?img=2",
                                              alt: "Online user",
                                              size: "lg",
                                              online: true
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "Online",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              src: "https://i.pravatar.cc/150?img=3",
                                              alt: "Offline user",
                                              size: "lg",
                                              online: false
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "Offline",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    })
                              ],
                              className: "flex items-center gap-8"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Comprehensive Examples",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              src: "https://i.pravatar.cc/150?img=4",
                                              alt: "User 1",
                                              size: "md",
                                              shape: "circular",
                                              online: true
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "User 1",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              fallback: "AB",
                                              size: "md",
                                              shape: "circular",
                                              online: true
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "User 2",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Avatar, {
                                              src: "https://i.pravatar.cc/150?img=6",
                                              alt: "User 3",
                                              size: "md",
                                              shape: "rounded",
                                              online: false
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "User 3",
                                              className: "mt-2 text-sm"
                                            })
                                      ],
                                      className: "flex flex-col items-center"
                                    })
                              ],
                              className: "grid grid-cols-3 gap-8"
                            })
                      ],
                      className: "mb-8"
                    })
              ]
            });
}

var AvatarDemo = {
  make: AvatarDemo$AvatarDemo
};

export {
  AvatarDemo ,
}
/* react/jsx-runtime Not a pure module */
