// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function ButtonGroupDemo$ButtonGroupDemo(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "ButtonGroup Demo",
                      className: "text-2xl font-bold mb-6 mt-12"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "ButtonGroup Sizes",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs(DesignSystem.ButtonGroup, {
                                      size: "sm",
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Button, {
                                              buttonType: "primary",
                                              text: "Primary"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.Button, {
                                              buttonType: "secondary",
                                              text: "Secondary"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.Button, {
                                              buttonType: "secondary",
                                              text: "Action"
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsxs(DesignSystem.ButtonGroup, {
                                      size: "md",
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Button, {
                                              buttonType: "primary",
                                              text: "Primary"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.Button, {
                                              buttonType: "secondary",
                                              text: "Secondary"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.Button, {
                                              buttonType: "secondary",
                                              text: "Action"
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsxs(DesignSystem.ButtonGroup, {
                                      size: "lg",
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.Button, {
                                              buttonType: "primary",
                                              text: "Primary"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.Button, {
                                              buttonType: "secondary",
                                              text: "Secondary"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.Button, {
                                              buttonType: "secondary",
                                              text: "Action"
                                            })
                                      ]
                                    })
                              ],
                              className: "flex flex-col gap-6"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "ButtonGroup Modes",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "Mode: singlePrimary (default)",
                                              className: "mb-2"
                                            }),
                                        JsxRuntime.jsxs(DesignSystem.ButtonGroup, {
                                              mode: "singlePrimary",
                                              children: [
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "primary",
                                                      text: "Primary"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "danger",
                                                      text: "Danger"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "success",
                                                      text: "Success"
                                                    })
                                              ]
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "Mode: allSecondary",
                                              className: "mb-2"
                                            }),
                                        JsxRuntime.jsxs(DesignSystem.ButtonGroup, {
                                              mode: "allSecondary",
                                              children: [
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "primary",
                                                      text: "Primary"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "danger",
                                                      text: "Danger"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "success",
                                                      text: "Success"
                                                    })
                                              ]
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "Mode: noTransform",
                                              className: "mb-2"
                                            }),
                                        JsxRuntime.jsxs(DesignSystem.ButtonGroup, {
                                              mode: "noTransform",
                                              children: [
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "primary",
                                                      text: "Primary"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "danger",
                                                      text: "Danger"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "success",
                                                      text: "Success"
                                                    })
                                              ]
                                            })
                                      ]
                                    })
                              ],
                              className: "flex flex-col gap-6"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Stacked vs Non-stacked",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "isStacked: true (default)",
                                              className: "mb-2"
                                            }),
                                        JsxRuntime.jsxs(DesignSystem.ButtonGroup, {
                                              isStacked: true,
                                              children: [
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "primary",
                                                      text: "First"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "secondary",
                                                      text: "Second"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "secondary",
                                                      text: "Third"
                                                    })
                                              ]
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "isStacked: false",
                                              className: "mb-2"
                                            }),
                                        JsxRuntime.jsxs(DesignSystem.ButtonGroup, {
                                              isStacked: false,
                                              children: [
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "primary",
                                                      text: "First"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "secondary",
                                                      text: "Second"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.Button, {
                                                      buttonType: "secondary",
                                                      text: "Third"
                                                    })
                                              ]
                                            })
                                      ]
                                    })
                              ],
                              className: "flex flex-col gap-6"
                            })
                      ],
                      className: "mb-8"
                    })
              ]
            });
}

var ButtonGroupDemo = {
  make: ButtonGroupDemo$ButtonGroupDemo
};

export {
  ButtonGroupDemo ,
}
/* react/jsx-runtime Not a pure module */
