// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as LucideReact from "lucide-react";
import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function ButtonDemo$ButtonDemo(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Button Variants Demo",
                      className: "text-2xl font-bold mb-6"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Button Typesss",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "primary",
                                      onClick: (function (param) {
                                          console.log("Primary clicked");
                                        }),
                                      text: "Primary Button"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "secondary",
                                      onClick: (function (param) {
                                          console.log("Secondary clicked");
                                        }),
                                      text: "Secondary Button"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "danger",
                                      onClick: (function (param) {
                                          console.log("Danger clicked");
                                        }),
                                      text: "Danger Button"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "success",
                                      onClick: (function (param) {
                                          console.log("Success clicked");
                                        }),
                                      text: "Success Button"
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Button Sizes",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "primary",
                                      size: "sm",
                                      text: "Small Button"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "primary",
                                      size: "md",
                                      text: "Medium Button"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "primary",
                                      size: "lg",
                                      text: "Large Button"
                                    })
                              ],
                              className: "flex flex-wrap items-center gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Button States",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "primary",
                                      text: "Enabled Button"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "primary",
                                      isDisabled: true,
                                      text: "Disabled Button"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "primary",
                                      text: "Loading",
                                      isLoading: true
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Button Subtypes",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "secondary",
                                      text: "Default Button",
                                      subType: "default"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "secondary",
                                      text: "Link Button",
                                      subType: "link"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "secondary",
                                      subType: "iconOnly",
                                      leftIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.ThumbsUp, {
                                                size: 18
                                              })),
                                      ariaLabel: "Icon only button"
                                    })
                              ],
                              className: "flex flex-wrap items-center gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Buttons with Icons",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "primary",
                                      text: "Left Icon",
                                      leftIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.ChevronLeft, {
                                                size: 18
                                              }))
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "primary",
                                      text: "Right Icon",
                                      rightIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.ChevronRight, {
                                                size: 18
                                              }))
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "primary",
                                      text: "Both Icons",
                                      leftIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.ChevronLeft, {
                                                size: 18
                                              })),
                                      rightIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.ChevronRight, {
                                                size: 18
                                              }))
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Icon Variants",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "primary",
                                      text: "Download",
                                      leftIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.Download, {
                                                size: 18
                                              }))
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "secondary",
                                      text: "Mail",
                                      leftIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.Mail, {
                                                size: 18,
                                                color: "#666"
                                              }))
                                    }),
                                JsxRuntime.jsx(DesignSystem.Button, {
                                      buttonType: "success",
                                      subType: "iconOnly",
                                      leftIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.Check, {
                                                size: 18
                                              })),
                                      ariaLabel: "Success"
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Full Width Button",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsx(DesignSystem.Button, {
                              buttonType: "primary",
                              text: "Full Width Button",
                              fullWidth: true
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Button with Children",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsx(DesignSystem.Button, {
                              buttonType: "success",
                              children: Caml_option.some(JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsx(LucideReact.Check, {
                                                size: 18,
                                                className: "mr-2"
                                              }),
                                          JsxRuntime.jsx("span", {
                                                children: "Custom Content"
                                              })
                                        ],
                                        className: "flex items-center"
                                      }))
                            })
                      ],
                      className: "mb-8"
                    })
              ]
            });
}

var ButtonDemo = {
  make: ButtonDemo$ButtonDemo
};

export {
  ButtonDemo ,
}
/* lucide-react Not a pure module */
