// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as LucideReact from "lucide-react";
import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function CheckboxDemo$CheckboxDemo(props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsChecked = match[1];
  var isChecked = match[0];
  var match$1 = React.useState(function () {
        return ["option1"];
      });
  var setGroupValues = match$1[1];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Checkbox Demo",
                      className: "text-2xl font-bold mb-6 mt-12"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Basic Checkbox",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      children: "Default Checkbox"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      defaultChecked: true,
                                      children: "Checked by default"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      isChecked: isChecked,
                                      onCheckedChange: (function (checked) {
                                          console.log("Checkbox changed:", checked);
                                        }),
                                      children: "Controlled Checkbox"
                                    })
                              ],
                              className: "flex flex-col gap-4"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Checkbox Sizes",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      size: "sm",
                                      children: "Small Checkbox"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      size: "md",
                                      children: "Medium Checkbox"
                                    })
                              ],
                              className: "flex flex-col gap-4"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Checkbox Positions",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      children: "Left Position (Default)",
                                      position: "left"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      children: "Right Position",
                                      position: "right"
                                    })
                              ],
                              className: "flex flex-col gap-4"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Checkbox States",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      children: "Normal Checkbox"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      isDisabled: true,
                                      children: "Disabled Checkbox"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      defaultChecked: true,
                                      isDisabled: true,
                                      children: "Disabled Checked Checkbox"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      required: true,
                                      children: "Required Checkbox"
                                    })
                              ],
                              className: "flex flex-col gap-4"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Checkbox with Additional Content",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      children: "Checkbox with subtext",
                                      subtext: "This is additional information about the checkbox"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      children: "Checkbox with right slot",
                                      rightSlot: Caml_option.some(JsxRuntime.jsx(LucideReact.Check, {
                                                size: 18,
                                                color: "green"
                                              }))
                                    })
                              ],
                              className: "flex flex-col gap-4"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Controlled Checkbox",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Checkbox, {
                                      isChecked: isChecked,
                                      onCheckedChange: (function (checked) {
                                          setIsChecked(function (param) {
                                                return checked;
                                              });
                                        }),
                                      children: Caml_option.some("Checkbox is " + (
                                            isChecked ? "checked" : "unchecked"
                                          ))
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Toggle Checkbox",
                                      className: "px-4 py-2 bg-blue-500 text-white rounded mt-2",
                                      onClick: (function (param) {
                                          setIsChecked(function (prev) {
                                                return !prev;
                                              });
                                        })
                                    })
                              ],
                              className: "flex flex-col gap-4"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Checkbox Group",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsx(DesignSystem.CheckboxGroup, {
                              label: "Select options",
                              name: "options",
                              value: match$1[0],
                              children: JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx(DesignSystem.Checkbox, {
                                            value: "option1",
                                            children: "Option 1"
                                          }),
                                      JsxRuntime.jsx(DesignSystem.Checkbox, {
                                            value: "option2",
                                            children: "Option 2"
                                          }),
                                      JsxRuntime.jsx(DesignSystem.Checkbox, {
                                            value: "option3",
                                            children: "Option 3"
                                          })
                                    ],
                                    className: "flex flex-col gap-3"
                                  }),
                              onChange: (function (e) {
                                  var values = e.values;
                                  setGroupValues(function (param) {
                                        return values;
                                      });
                                  console.log("Selected values:", values);
                                })
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Disabled Checkbox Group",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsx(DesignSystem.CheckboxGroup, {
                              label: "Disabled options group",
                              name: "disabled-options",
                              defaultValue: ["option1"],
                              children: JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx(DesignSystem.Checkbox, {
                                            value: "option1",
                                            children: "Option 1"
                                          }),
                                      JsxRuntime.jsx(DesignSystem.Checkbox, {
                                            value: "option2",
                                            children: "Option 2"
                                          })
                                    ],
                                    className: "flex flex-col gap-3"
                                  }),
                              isDisabled: true
                            })
                      ],
                      className: "mb-8"
                    })
              ]
            });
}

var CheckboxDemo = {
  make: CheckboxDemo$CheckboxDemo
};

export {
  CheckboxDemo ,
}
/* react Not a pure module */
