// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function CorrectDropdownDemo(props) {
  var match = React.useState(function () {
        return [];
      });
  var selectedItems = match[0];
  React.useState(function () {
        return false;
      });
  React.useEffect((function () {
          console.log("Selected items updated in CorrectDropdownDemo: ");
          console.log(selectedItems);
          console.log("Count: " + String(selectedItems.length));
        }), [selectedItems]);
  var multiSelectMenuItems = [
    {
      id: "1",
      text: "Option 1",
      menuType: "MULTI_SELECT"
    },
    {
      id: "2",
      text: "Option 2",
      menuType: "MULTI_SELECT"
    },
    {
      id: "3",
      text: "Option 3",
      menuType: "MULTI_SELECT"
    }
  ];
  var selectedItemsStr = Belt_Array.joinWith(selectedItems, ",", (function (x) {
          return x;
        }));
  var selectedCount = selectedItems.length;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Correct Dropdown Demo",
                      className: "text-2xl font-bold mb-6"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("h2", {
                                    children: "Multi-select MenuDropdown",
                                    className: "text-xl font-semibold mb-4"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("h3", {
                                                    children: "Count Display (hasContainer)",
                                                    className: "text-lg  font-medium mb-2"
                                                  }),
                                              JsxRuntime.jsx("div", {
                                                    children: (console.log("Rendering Count dropdown with:"), console.log("selectedOption", selectedItemsStr), console.log("selectedCount", selectedCount), JsxRuntime.jsx(DesignSystem.Dropdown, {
                                                            dropdownType: "multiSelect",
                                                            selectionType: "count",
                                                            hasLabel: true,
                                                            hasHint: true,
                                                            label: "Multi Select (Count)",
                                                            hint: "Select multiple options",
                                                            placeholder: "Select options",
                                                            menuItems: multiSelectMenuItems
                                                          })),
                                                    className: "flex flex-wrap gap-4"
                                                  })
                                            ]
                                          }),
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("h3", {
                                                    children: "Text Display (hasContainer)",
                                                    className: "text-lg font-medium mb-2"
                                                  }),
                                              JsxRuntime.jsx("div", {
                                                    children: JsxRuntime.jsx(DesignSystem.Dropdown, {
                                                          id: "multi-select-text-correct",
                                                          dropdownType: "multiSelect",
                                                          selectionType: "text",
                                                          hasLabel: true,
                                                          hasHint: true,
                                                          label: "Multi Select (Text)",
                                                          hint: "Select multiple options",
                                                          placeholder: "Select options",
                                                          menuItems: multiSelectMenuItems
                                                        }),
                                                    className: "flex flex-wrap gap-4"
                                                  })
                                            ]
                                          })
                                    ],
                                    className: "space-y-8"
                                  }),
                              JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsx("p", {
                                          children: selectedItems.length === 0 ? "No items selected" : "Selected items: " + Belt_Array.joinWith(selectedItems, ", ", (function (x) {
                                                    return x;
                                                  })),
                                          className: "font-medium"
                                        }),
                                    className: "mt-4"
                                  })
                            ]
                          }),
                      className: "space-y-8"
                    })
              ],
              className: "space-y-10 p-6"
            });
}

var make = CorrectDropdownDemo;

export {
  make ,
}
/* react Not a pure module */
