// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function DropdownInputDemo$DropdownInputDemo(props) {
  var match = React.useState(function () {
        return "";
      });
  var setCurrencyValue = match[1];
  var currencyValue = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setCurrencyInputValue = match$1[1];
  var currencyInputValue = match$1[0];
  var match$2 = React.useState(function () {
        return "";
      });
  var setCountryValue = match$2[1];
  var countryValue = match$2[0];
  var match$3 = React.useState(function () {
        return "";
      });
  var setCountryInputValue = match$3[1];
  var countryInputValue = match$3[0];
  var match$4 = React.useState(function () {
        return "";
      });
  var setUserRoleValue = match$4[1];
  var userRoleValue = match$4[0];
  var match$5 = React.useState(function () {
        return "";
      });
  var setUserRoleInputValue = match$5[1];
  var userRoleInputValue = match$5[0];
  var currencyOptions = [
    {
      label: "USD - US Dollar",
      value: "USD"
    },
    {
      label: "EUR - Euro",
      value: "EUR"
    },
    {
      label: "GBP - British Pound",
      value: "GBP"
    },
    {
      label: "JPY - Japanese Yen",
      value: "JPY"
    },
    {
      label: "INR - Indian Rupee",
      value: "INR"
    }
  ];
  var countryOptions = [
    {
      label: "United States",
      value: "USA"
    },
    {
      label: "United Kingdom",
      value: "UK"
    },
    {
      label: "France",
      value: "FRA"
    },
    {
      label: "Germany",
      value: "GER"
    },
    {
      label: "Japan",
      value: "JPN"
    },
    {
      label: "India",
      value: "IND"
    },
    {
      label: "Australia",
      value: "AUS"
    },
    {
      label: "Canada",
      value: "CAN"
    }
  ];
  var userRoleOptions = [
    {
      label: "Admin",
      value: "admin"
    },
    {
      label: "User",
      value: "user"
    },
    {
      label: "Editor",
      value: "editor"
    },
    {
      label: "Viewer",
      value: "viewer"
    },
    {
      label: "Manager",
      value: "manager"
    }
  ];
  var paymentMethodOptions = [
    {
      label: "Credit Card",
      value: "credit_card"
    },
    {
      label: "Debit Card",
      value: "debit_card"
    },
    {
      label: "PayPal",
      value: "paypal"
    },
    {
      label: "Bank Transfer",
      value: "bank_transfer"
    },
    {
      label: "Cash",
      value: "cash"
    }
  ];
  var handleCurrencyChange = function (value) {
    setCurrencyInputValue(function (param) {
          return value;
        });
    console.log("Currency input changed: " + value);
  };
  var handleCurrencySelect = function (option) {
    setCurrencyValue(function (param) {
          return option.value;
        });
    console.log("Currency selected: " + option.label + " (" + option.value + ")");
  };
  var handleCountryChange = function (value) {
    setCountryInputValue(function (param) {
          return value;
        });
    console.log("Country input changed: " + value);
  };
  var handleCountrySelect = function (option) {
    setCountryValue(function (param) {
          return option.value;
        });
    console.log("Country selected: " + option.label + " (" + option.value + ")");
  };
  var handleUserRoleChange = function (value) {
    setUserRoleInputValue(function (param) {
          return value;
        });
    console.log("User role input changed: " + value);
  };
  var handleUserRoleSelect = function (option) {
    setUserRoleValue(function (param) {
          return option.value;
        });
    console.log("User role selected: " + option.label + " (" + option.value + ")");
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "DropdownInput Components",
                      className: "text-2xl font-bold"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Basic DropdownInput Examples",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "Currency",
                                      placeholder: "Enter or select currency",
                                      value: currencyValue,
                                      inputValue: currencyInputValue,
                                      options: currencyOptions,
                                      onOptionSelect: handleCurrencySelect,
                                      onChange: handleCurrencyChange,
                                      dropdownPlaceholder: "Select currency",
                                      className: "w-full"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "Country",
                                      placeholder: "Enter or select country",
                                      value: countryValue,
                                      inputValue: countryInputValue,
                                      options: countryOptions,
                                      onOptionSelect: handleCountrySelect,
                                      onChange: handleCountryChange,
                                      dropdownPlaceholder: "Select country",
                                      dropdownPosition: "right",
                                      className: "w-full"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "User Role",
                                      placeholder: "Enter or select role",
                                      value: userRoleValue,
                                      inputValue: userRoleInputValue,
                                      options: userRoleOptions,
                                      onOptionSelect: handleUserRoleSelect,
                                      onChange: handleUserRoleChange,
                                      showSelectedOptionInInput: true,
                                      dropdownPlaceholder: "Select role",
                                      className: "w-full"
                                    })
                              ],
                              className: "space-y-4 max-w-md"
                            })
                      ],
                      className: "border rounded p-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "DropdownInput States",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "Default State",
                                      placeholder: "Default state",
                                      state: "default",
                                      options: currencyOptions,
                                      dropdownPlaceholder: "Select"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "Hover State",
                                      placeholder: "Hover state",
                                      state: "hover",
                                      options: currencyOptions,
                                      dropdownPlaceholder: "Select"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "Focused State",
                                      placeholder: "Focused state",
                                      state: "focused",
                                      options: currencyOptions,
                                      dropdownPlaceholder: "Select"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "Filled State",
                                      placeholder: "Filled state",
                                      state: "filled",
                                      value: "USD",
                                      inputValue: "US Dollar",
                                      options: currencyOptions,
                                      dropdownPlaceholder: "Select"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "Error State",
                                      placeholder: "Error state",
                                      state: "error",
                                      errorMessage: "This field has an error",
                                      options: currencyOptions,
                                      dropdownPlaceholder: "Select"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "Success State",
                                      placeholder: "Success state",
                                      state: "success",
                                      value: "USD",
                                      inputValue: "US Dollar",
                                      successMessage: "This field is valid",
                                      options: currencyOptions,
                                      dropdownPlaceholder: "Select"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "Disabled State",
                                      placeholder: "Disabled state",
                                      state: "disabled",
                                      options: currencyOptions,
                                      dropdownPlaceholder: "Select"
                                    })
                              ],
                              className: "grid grid-cols-1 md:grid-cols-2 gap-4"
                            })
                      ],
                      className: "border rounded p-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "DropdownInput Configurations",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "With Icons",
                                      placeholder: "Select payment method",
                                      options: paymentMethodOptions,
                                      dropdownPlaceholder: "Payment method",
                                      className: "w-full"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "With Dropdown Width",
                                      placeholder: "Enter or select currency",
                                      options: currencyOptions,
                                      dropdownWidth: "120px",
                                      dropdownPlaceholder: "Currency",
                                      className: "w-full"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "Right Dropdown",
                                      placeholder: "Enter or select country",
                                      options: countryOptions,
                                      dropdownPlaceholder: "Country",
                                      dropdownPosition: "right",
                                      className: "w-full"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "Show Selected in Input",
                                      placeholder: "Select role",
                                      options: userRoleOptions,
                                      showSelectedOptionInInput: true,
                                      dropdownPlaceholder: "Role",
                                      className: "w-full"
                                    })
                              ],
                              className: "space-y-4 max-w-md"
                            })
                      ],
                      className: "border rounded p-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "DropdownInput with Additional Elements",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "With Sublabel",
                                      placeholder: "Enter or select an option",
                                      sublabel: "Additional information about this field",
                                      options: currencyOptions,
                                      dropdownPlaceholder: "Select",
                                      className: "w-full"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      hintText: "This is a hint to help you fill this field",
                                      label: "With Hint",
                                      placeholder: "Enter or select an option",
                                      options: currencyOptions,
                                      dropdownPlaceholder: "Select",
                                      className: "w-full"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "Mandatory Field",
                                      mandatory: true,
                                      placeholder: "This field is required",
                                      options: currencyOptions,
                                      dropdownPlaceholder: "Select",
                                      className: "w-full"
                                    }),
                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                      label: "With Info Tooltip",
                                      placeholder: "Hover over the info icon",
                                      infoTooltip: "This tooltip provides additional information about the field",
                                      options: currencyOptions,
                                      dropdownPlaceholder: "Select",
                                      className: "w-full"
                                    })
                              ],
                              className: "space-y-4 max-w-md"
                            })
                      ],
                      className: "border rounded p-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "DropdownInput Use Cases",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("h3", {
                                              children: "Payment Form",
                                              className: "text-lg font-medium mb-2"
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                                      label: "Currency",
                                                      mandatory: true,
                                                      placeholder: "Enter or select currency",
                                                      value: currencyValue,
                                                      inputValue: currencyInputValue,
                                                      options: currencyOptions,
                                                      onOptionSelect: handleCurrencySelect,
                                                      onChange: handleCurrencyChange,
                                                      dropdownWidth: "100px",
                                                      dropdownPlaceholder: "Currency",
                                                      className: "w-full"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                                      label: "Payment Method",
                                                      mandatory: true,
                                                      placeholder: "Select payment method",
                                                      options: paymentMethodOptions,
                                                      showSelectedOptionInInput: true,
                                                      dropdownPlaceholder: "Select",
                                                      className: "w-full"
                                                    })
                                              ],
                                              className: "grid grid-cols-1 gap-4"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: JsxRuntime.jsx("button", {
                                                    children: "Process Payment",
                                                    className: "px-4 py-2 rounded-md text-white font-medium " + (
                                                      currencyValue.length > 0 ? "bg-blue-600 hover:bg-blue-700" : "bg-gray-300 cursor-not-allowed"
                                                    ),
                                                    disabled: currencyValue.length === 0,
                                                    onClick: (function (param) {
                                                        console.log("Processing payment...");
                                                      })
                                                  }),
                                              className: "mt-4"
                                            })
                                      ],
                                      className: "border p-4 rounded-lg bg-gray-50"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("h3", {
                                              children: "User Profile",
                                              className: "text-lg font-medium mb-2"
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                                      label: "Country",
                                                      placeholder: "Enter or select country",
                                                      value: countryValue,
                                                      inputValue: countryInputValue,
                                                      options: countryOptions,
                                                      onOptionSelect: handleCountrySelect,
                                                      onChange: handleCountryChange,
                                                      dropdownPlaceholder: "Select country",
                                                      className: "w-full"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.DropdownInput, {
                                                      label: "Role",
                                                      placeholder: "Enter or select role",
                                                      value: userRoleValue,
                                                      inputValue: userRoleInputValue,
                                                      options: userRoleOptions,
                                                      onOptionSelect: handleUserRoleSelect,
                                                      onChange: handleUserRoleChange,
                                                      dropdownPlaceholder: "Select role",
                                                      className: "w-full"
                                                    })
                                              ],
                                              className: "grid grid-cols-1 gap-4"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: JsxRuntime.jsx("button", {
                                                    children: "Save Profile",
                                                    className: "px-4 py-2 rounded-md text-white font-medium " + (
                                                      countryValue.length > 0 && userRoleValue.length > 0 ? "bg-blue-600 hover:bg-blue-700" : "bg-gray-300 cursor-not-allowed"
                                                    ),
                                                    disabled: countryValue.length === 0 || userRoleValue.length === 0,
                                                    onClick: (function (param) {
                                                        console.log("Saving user profile...");
                                                      })
                                                  }),
                                              className: "mt-4"
                                            })
                                      ],
                                      className: "border p-4 rounded-lg bg-gray-50"
                                    })
                              ],
                              className: "space-y-6"
                            })
                      ],
                      className: "border rounded p-4"
                    })
              ],
              className: "p-4 space-y-8"
            });
}

var DropdownInputDemo = {
  make: DropdownInputDemo$DropdownInputDemo
};

var $$default = DropdownInputDemo$DropdownInputDemo;

export {
  DropdownInputDemo ,
  $$default as default,
}
/* react Not a pure module */
