// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as LucideReact from "lucide-react";
import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function MenuDropdownDemo(props) {
  var basicMenuItems = [
    {
      id: "1",
      text: "Option 1",
      className: undefined,
      disabled: undefined,
      menuType: "DEFAULT",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: undefined,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: undefined,
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    },
    {
      id: "2",
      text: "Option 2",
      className: undefined,
      disabled: undefined,
      menuType: "DEFAULT",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: undefined,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: undefined,
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    },
    {
      id: "3",
      text: "Option 3",
      className: undefined,
      disabled: undefined,
      menuType: "DEFAULT",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: undefined,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: undefined,
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    }
  ];
  var iconMenuItems = [
    {
      id: "1",
      text: "Profile",
      className: undefined,
      disabled: undefined,
      menuType: "DEFAULT",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: true,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                size: 16
              })),
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    },
    {
      id: "2",
      text: "Settings",
      className: undefined,
      disabled: undefined,
      menuType: "DEFAULT",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: true,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.Settings, {
                size: 16
              })),
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    },
    {
      id: "3",
      text: "Help",
      className: undefined,
      disabled: undefined,
      menuType: "DEFAULT",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: true,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.HelpCircle, {
                size: 16
              })),
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    }
  ];
  var multiSelectMenuItems = [
    {
      id: "1",
      text: "Option 1",
      className: undefined,
      disabled: undefined,
      menuType: "MULTI_SELECT",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: undefined,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: undefined,
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: true,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    },
    {
      id: "2",
      text: "Option 2",
      className: undefined,
      disabled: undefined,
      menuType: "MULTI_SELECT",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: undefined,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: undefined,
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: true,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    },
    {
      id: "3",
      text: "Option 3",
      className: undefined,
      disabled: undefined,
      menuType: "MULTI_SELECT",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: undefined,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: undefined,
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: true,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    }
  ];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "Dropdown Examples",
                      className: "text-2xl font-semibold"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h3", {
                              children: "Dropdown Types",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h4", {
                                      children: "1. Single Select Dropdown",
                                      className: "text-lg font-medium mb-4"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "Default (HAS_CONTAINER)",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "singleSelect",
                                                      hasLabel: true,
                                                      hasHint: true,
                                                      label: "Single Select",
                                                      hint: "Select one option",
                                                      placeholder: "Select an option",
                                                      menuItems: basicMenuItems
                                                    })
                                              ]
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "NO_CONTAINER Variant",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "singleSelect",
                                                      subType: "noContainer",
                                                      placeholder: "Select an option",
                                                      menuItems: basicMenuItems
                                                    })
                                              ]
                                            })
                                      ],
                                      className: "flex flex-wrap gap-8"
                                    })
                              ],
                              className: "mt-6 pb-6 border-b border-gray-200"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h4", {
                                      children: "2. Icon Only Dropdown",
                                      className: "text-lg font-medium mb-4"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "Default (HAS_CONTAINER)",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "iconOnly",
                                                      hasLabel: true,
                                                      hasHint: true,
                                                      hasLeftIcon: true,
                                                      leftIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                                                                size: 16
                                                              })),
                                                      label: "Icon Only",
                                                      hint: "Click icon to open",
                                                      menuItems: iconMenuItems
                                                    })
                                              ]
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "NO_CONTAINER Variant",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "iconOnly",
                                                      subType: "noContainer",
                                                      hasLeftIcon: true,
                                                      leftIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                                                                size: 16
                                                              })),
                                                      menuItems: iconMenuItems
                                                    })
                                              ]
                                            })
                                      ],
                                      className: "flex flex-wrap gap-8"
                                    })
                              ],
                              className: "mt-6 pb-6 border-b border-gray-200"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h4", {
                                      children: "3. Multi Select Dropdown",
                                      className: "text-lg font-medium mb-4"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "Count Display (HAS_CONTAINER)",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "multiSelect",
                                                      selectionType: "count",
                                                      hasLabel: true,
                                                      hasHint: true,
                                                      label: "Multi Select (Count)",
                                                      hint: "Select multiple options",
                                                      placeholder: "Select options",
                                                      menuItems: multiSelectMenuItems
                                                    })
                                              ]
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "Text Display (HAS_CONTAINER)",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "multiSelect",
                                                      selectionType: "text",
                                                      hasLabel: true,
                                                      hasHint: true,
                                                      label: "Multi Select (Text)",
                                                      hint: "Select multiple options",
                                                      placeholder: "Select options",
                                                      menuItems: multiSelectMenuItems
                                                    })
                                              ]
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "NO_CONTAINER Variant",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "multiSelect",
                                                      subType: "noContainer",
                                                      placeholder: "Select options",
                                                      menuItems: multiSelectMenuItems
                                                    })
                                              ]
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "NO_CONTAINER with Text Display",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "multiSelect",
                                                      subType: "noContainer",
                                                      selectionType: "text",
                                                      placeholder: "Text display",
                                                      menuItems: multiSelectMenuItems
                                                    })
                                              ]
                                            })
                                      ],
                                      className: "flex flex-wrap gap-8"
                                    })
                              ],
                              className: "mt-6 pb-6 border-b border-gray-200"
                            })
                      ],
                      className: "mt-6"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h3", {
                              children: "Dropdown Subtypes",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h4", {
                                      children: "1. HAS_CONTAINER Subtype",
                                      className: "text-lg font-medium mb-4"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "Shows label, sublabel, and hint text",
                                      className: "text-gray-600 mb-4"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                              subType: "hasContainer",
                                              hasLabel: true,
                                              label: "Regular Label",
                                              placeholder: "Basic label",
                                              menuItems: basicMenuItems
                                            }),
                                        JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                              subType: "hasContainer",
                                              hasLabel: true,
                                              hasSubLabel: true,
                                              label: "With Sublabel",
                                              subLabel: "(optional)",
                                              placeholder: "Label and sublabel",
                                              menuItems: basicMenuItems
                                            }),
                                        JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                              subType: "hasContainer",
                                              hasLabel: true,
                                              hasHint: true,
                                              label: "With Hint",
                                              hint: "This is a helpful hint text",
                                              placeholder: "Label and hint",
                                              menuItems: basicMenuItems
                                            }),
                                        JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                              subType: "hasContainer",
                                              hasLabel: true,
                                              mandatory: true,
                                              label: "Required Field",
                                              placeholder: "With required indicator",
                                              menuItems: basicMenuItems
                                            })
                                      ],
                                      className: "flex flex-col space-y-4"
                                    })
                              ],
                              className: "mt-6 pb-6 border-b border-gray-200"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h4", {
                                      children: "2. NO_CONTAINER Subtype",
                                      className: "text-lg font-medium mb-4"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "Standalone dropdown with no labels, hints, or borders",
                                      className: "text-gray-600 mb-4"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "Single Select",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      subType: "noContainer",
                                                      placeholder: "No container dropdown",
                                                      menuItems: basicMenuItems
                                                    })
                                              ]
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "Multi Select",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "multiSelect",
                                                      subType: "noContainer",
                                                      placeholder: "No container multiselect",
                                                      menuItems: multiSelectMenuItems
                                                    })
                                              ]
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "Icon Only",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "iconOnly",
                                                      subType: "noContainer",
                                                      hasLeftIcon: true,
                                                      leftIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                                                                size: 16
                                                              })),
                                                      menuItems: iconMenuItems
                                                    })
                                              ]
                                            })
                                      ],
                                      className: "flex flex-wrap gap-8"
                                    })
                              ],
                              className: "mt-6"
                            })
                      ],
                      className: "mt-10"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h3", {
                              children: "Dropdown Sizes",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("p", {
                                              children: "Small (sm)",
                                              className: "text-sm text-gray-600 mb-2"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                              size: "sm",
                                              hasLabel: true,
                                              label: "Small Dropdown",
                                              placeholder: "Small",
                                              menuItems: basicMenuItems
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("p", {
                                              children: "Medium (md)",
                                              className: "text-sm text-gray-600 mb-2"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                              size: "md",
                                              hasLabel: true,
                                              label: "Medium Dropdown",
                                              placeholder: "Medium",
                                              menuItems: basicMenuItems
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("p", {
                                              children: "Large (lg)",
                                              className: "text-sm text-gray-600 mb-2"
                                            }),
                                        JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                              size: "lg",
                                              hasLabel: true,
                                              label: "Large Dropdown",
                                              placeholder: "Large",
                                              menuItems: basicMenuItems
                                            })
                                      ]
                                    })
                              ],
                              className: "flex flex-wrap gap-6 items-end"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h4", {
                                      children: "Icon Size Comparison",
                                      className: "text-lg font-medium mb-4"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "Small (sm)",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "iconOnly",
                                                      size: "sm",
                                                      hasLeftIcon: true,
                                                      leftIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                                                                size: 16
                                                              })),
                                                      menuItems: basicMenuItems
                                                    })
                                              ]
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "Medium (md)",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "iconOnly",
                                                      size: "md",
                                                      hasLeftIcon: true,
                                                      leftIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                                                                size: 16
                                                              })),
                                                      menuItems: basicMenuItems
                                                    })
                                              ]
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: "Large (lg)",
                                                      className: "text-sm text-gray-600 mb-2"
                                                    }),
                                                JsxRuntime.jsx(DesignSystem.MenuDropdown, {
                                                      dropdownType: "iconOnly",
                                                      size: "lg",
                                                      hasLeftIcon: true,
                                                      leftIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                                                                size: 16
                                                              })),
                                                      menuItems: basicMenuItems
                                                    })
                                              ]
                                            })
                                      ],
                                      className: "flex flex-wrap gap-6 items-end"
                                    })
                              ],
                              className: "mt-8"
                            })
                      ],
                      className: "mt-10"
                    })
              ]
            });
}

var make = MenuDropdownDemo;

export {
  make ,
}
/* lucide-react Not a pure module */
