// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as LucideReact from "lucide-react";
import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function MenuDemo(props) {
  var match = React.useState(function () {
        return [];
      });
  var setSelectedItems = match[1];
  var selectedItems = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setSearchTerm = match$1[1];
  var basicMenuItems = [
    {
      id: "1",
      text: "Profile",
      className: undefined,
      disabled: undefined,
      menuType: "DEFAULT",
      state: undefined,
      action: undefined,
      onClick: (function () {
          console.log("Profile clicked");
        }),
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: true,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                size: 16
              })),
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    },
    {
      id: "2",
      text: "Settings",
      className: undefined,
      disabled: undefined,
      menuType: "DEFAULT",
      state: undefined,
      action: undefined,
      onClick: (function () {
          console.log("Settings clicked");
        }),
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: true,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.Settings, {
                size: 16
              })),
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    },
    {
      id: "3",
      text: "Help",
      className: undefined,
      disabled: undefined,
      menuType: "DEFAULT",
      state: undefined,
      action: undefined,
      onClick: (function () {
          console.log("Help clicked");
        }),
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: true,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.HelpCircle, {
                size: 16
              })),
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    }
  ];
  var menuWithSubmenuItems = [
    {
      id: "1",
      text: "Profile",
      className: undefined,
      disabled: undefined,
      menuType: "SUBMENU",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: true,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                size: 16
              })),
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: true,
      submenuItems: [
        {
          id: "1-1",
          text: "View Profile",
          className: undefined,
          disabled: undefined,
          menuType: "DEFAULT",
          state: undefined,
          action: undefined,
          onClick: (function () {
              console.log("View Profile clicked");
            }),
          onMouseEnter: undefined,
          onMouseLeave: undefined,
          hasSlotL: true,
          hasSlotR1: undefined,
          hasSlotR2: undefined,
          slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                    size: 16
                  })),
          slotR1: undefined,
          slotR2: undefined,
          hasShortcut: undefined,
          shortcutValue: undefined,
          isMultiSelect: undefined,
          isSelected: undefined,
          hasSubmenu: undefined,
          submenuItems: undefined,
          parentId: "1"
        },
        {
          id: "1-2",
          text: "Edit Profile",
          className: undefined,
          disabled: undefined,
          menuType: "SUBMENU",
          state: undefined,
          action: undefined,
          onClick: undefined,
          onMouseEnter: undefined,
          onMouseLeave: undefined,
          hasSlotL: true,
          hasSlotR1: undefined,
          hasSlotR2: undefined,
          slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.Settings, {
                    size: 16
                  })),
          slotR1: undefined,
          slotR2: undefined,
          hasShortcut: undefined,
          shortcutValue: undefined,
          isMultiSelect: undefined,
          isSelected: undefined,
          hasSubmenu: true,
          submenuItems: [
            {
              id: "1-2-1",
              text: "Personal Info",
              className: undefined,
              disabled: undefined,
              menuType: "DEFAULT",
              state: undefined,
              action: undefined,
              onClick: (function () {
                  console.log("Personal Info clicked");
                }),
              onMouseEnter: undefined,
              onMouseLeave: undefined,
              hasSlotL: true,
              hasSlotR1: undefined,
              hasSlotR2: undefined,
              slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                        size: 16
                      })),
              slotR1: undefined,
              slotR2: undefined,
              hasShortcut: undefined,
              shortcutValue: undefined,
              isMultiSelect: undefined,
              isSelected: undefined,
              hasSubmenu: undefined,
              submenuItems: undefined,
              parentId: "1-2"
            },
            {
              id: "1-2-2",
              text: "Preferences",
              className: undefined,
              disabled: undefined,
              menuType: "DEFAULT",
              state: undefined,
              action: undefined,
              onClick: (function () {
                  console.log("Preferences clicked");
                }),
              onMouseEnter: undefined,
              onMouseLeave: undefined,
              hasSlotL: true,
              hasSlotR1: undefined,
              hasSlotR2: undefined,
              slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.Settings, {
                        size: 16
                      })),
              slotR1: undefined,
              slotR2: undefined,
              hasShortcut: undefined,
              shortcutValue: undefined,
              isMultiSelect: undefined,
              isSelected: undefined,
              hasSubmenu: undefined,
              submenuItems: undefined,
              parentId: "1-2"
            }
          ],
          parentId: "1"
        }
      ],
      parentId: undefined
    },
    {
      id: "2",
      text: "Notifications",
      className: undefined,
      disabled: undefined,
      menuType: "SUBMENU",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: true,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.Bell, {
                size: 16
              })),
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: true,
      submenuItems: [{
          id: "2-1",
          text: "All Notifications",
          className: undefined,
          disabled: undefined,
          menuType: "DEFAULT",
          state: undefined,
          action: undefined,
          onClick: (function () {
              console.log("All Notifications clicked");
            }),
          onMouseEnter: undefined,
          onMouseLeave: undefined,
          hasSlotL: true,
          hasSlotR1: undefined,
          hasSlotR2: undefined,
          slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.Bell, {
                    size: 16
                  })),
          slotR1: undefined,
          slotR2: undefined,
          hasShortcut: undefined,
          shortcutValue: undefined,
          isMultiSelect: undefined,
          isSelected: undefined,
          hasSubmenu: undefined,
          submenuItems: undefined,
          parentId: "2"
        }],
      parentId: undefined
    }
  ];
  var multiSelectMenuItems = [
    {
      id: "1",
      text: "Option 1",
      className: undefined,
      disabled: undefined,
      menuType: "MULTI_SELECT",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: undefined,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: undefined,
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: true,
      isSelected: selectedItems.includes("1"),
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    },
    {
      id: "2",
      text: "Option 2",
      className: undefined,
      disabled: undefined,
      menuType: "MULTI_SELECT",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: undefined,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: undefined,
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: true,
      isSelected: selectedItems.includes("2"),
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    },
    {
      id: "3",
      text: "Option 3",
      className: undefined,
      disabled: undefined,
      menuType: "MULTI_SELECT",
      state: undefined,
      action: undefined,
      onClick: undefined,
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: undefined,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: undefined,
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: true,
      isSelected: selectedItems.includes("3"),
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    }
  ];
  var menuWithActionsItems = [
    {
      id: "1",
      text: "Edit Profile",
      className: undefined,
      disabled: undefined,
      menuType: "ACTION",
      state: undefined,
      action: "PRIMARY",
      onClick: (function () {
          console.log("Edit Profile clicked");
        }),
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: true,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                size: 16
              })),
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    },
    {
      id: "2",
      text: "Delete Account",
      className: undefined,
      disabled: undefined,
      menuType: "ACTION",
      state: undefined,
      action: "DANGER",
      onClick: (function () {
          console.log("Delete Account clicked");
        }),
      onMouseEnter: undefined,
      onMouseLeave: undefined,
      hasSlotL: true,
      hasSlotR1: undefined,
      hasSlotR2: undefined,
      slotL: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                size: 16
              })),
      slotR1: undefined,
      slotR2: undefined,
      hasShortcut: undefined,
      shortcutValue: undefined,
      isMultiSelect: undefined,
      isSelected: undefined,
      hasSubmenu: undefined,
      submenuItems: undefined,
      parentId: undefined
    }
  ];
  var handleSelectionChange = function (items) {
    setSelectedItems(function (param) {
          return items;
        });
    console.log("Selected items: " + items.join(", "));
  };
  var handleSearchTermChange = function (term) {
    setSearchTerm(function (param) {
          return term;
        });
    console.log("Search term: " + term);
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "Menu Examples",
                      className: "text-2xl font-semibold"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h3", {
                              children: "Basic Menu",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsx(DesignSystem.Menu, {
                              items: basicMenuItems,
                              onItemClick: (function (item) {
                                  console.log("Clicked: " + item.text);
                                })
                            })
                      ],
                      className: "mt-6"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h3", {
                              children: "Menu with Submenu",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsx(DesignSystem.Menu, {
                              items: menuWithSubmenuItems,
                              onItemClick: (function (item) {
                                  console.log("Clicked: " + item.text);
                                })
                            })
                      ],
                      className: "mt-6"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h3", {
                              children: "Multi-select Menu",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsx(DesignSystem.Menu, {
                              menuType: "MULTI_SELECT",
                              items: multiSelectMenuItems,
                              selectedItems: selectedItems,
                              onSelectionChange: handleSelectionChange
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("p", {
                                      children: "Selected items:",
                                      className: "font-medium"
                                    }),
                                selectedItems.length > 0 ? JsxRuntime.jsx("ul", {
                                        children: selectedItems.map(function (id) {
                                              var item = multiSelectMenuItems.find(function (item) {
                                                    return item.id === id;
                                                  });
                                              if (item !== undefined) {
                                                return JsxRuntime.jsx("li", {
                                                            children: item.text
                                                          }, id);
                                              } else {
                                                return null;
                                              }
                                            }),
                                        className: "list-disc pl-5 mt-2"
                                      }) : JsxRuntime.jsx("p", {
                                        children: "No items selected",
                                        className: "text-gray-500"
                                      })
                              ],
                              className: "mt-4"
                            })
                      ],
                      className: "mt-6"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h3", {
                              children: "Menu with Search",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsx(DesignSystem.Menu, {
                              hasSearch: true,
                              items: basicMenuItems,
                              searchPlaceholder: "Search items...",
                              searchTerm: match$1[0],
                              onSearchTermChange: handleSearchTermChange
                            })
                      ],
                      className: "mt-6"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h3", {
                              children: "Menu with Actions",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsx(DesignSystem.Menu, {
                              items: menuWithActionsItems
                            })
                      ],
                      className: "mt-6"
                    })
              ],
              className: "p-6"
            });
}

var make = MenuDemo;

export {
  make ,
}
/* react Not a pure module */
