// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function MenuDemo(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("h1", {
                    children: "Menu Demo"
                  })
            });
}

var make = MenuDemo;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
