// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as LucideReact from "lucide-react";
import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function ModalDemo$ModalDemo(props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsModalOpen = match[1];
  var match$1 = React.useState(function () {
        return false;
      });
  var setIsCustomHeaderModalOpen = match$1[1];
  var match$2 = React.useState(function () {
        return false;
      });
  var setIsCustomFooterModalOpen = match$2[1];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Modal Demo",
                      className: "text-2xl font-bold mb-6 mt-12"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Basic Modal",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "Open Basic Modal",
                                      className: "px-4 py-2 bg-blue-500 text-white rounded",
                                      onClick: (function (param) {
                                          setIsModalOpen(function (param) {
                                                return true;
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx(DesignSystem.Modal, {
                                      isOpen: match[0],
                                      onClose: (function () {
                                          setIsModalOpen(function (param) {
                                                return false;
                                              });
                                        }),
                                      title: "Basic Modal Title",
                                      subtitle: "This is a subtitle for the modal",
                                      children: JsxRuntime.jsx("div", {
                                            children: "This is the content of the modal. You can put any React element here.",
                                            className: "p-4"
                                          }),
                                      primaryButtonText: "Confirm",
                                      secondaryButtonText: "Cancel",
                                      onPrimaryButtonClick: (function () {
                                          console.log("Primary button clicked");
                                          setIsModalOpen(function (param) {
                                                return false;
                                              });
                                        }),
                                      onSecondaryButtonClick: (function () {
                                          console.log("Secondary button clicked");
                                          setIsModalOpen(function (param) {
                                                return false;
                                              });
                                        })
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Modal with Custom Header",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "Open Modal with Custom Header",
                                      className: "px-4 py-2 bg-blue-500 text-white rounded",
                                      onClick: (function (param) {
                                          setIsCustomHeaderModalOpen(function (param) {
                                                return true;
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx(DesignSystem.Modal, {
                                      isOpen: match$1[0],
                                      onClose: (function () {
                                          setIsCustomHeaderModalOpen(function (param) {
                                                return false;
                                              });
                                        }),
                                      children: JsxRuntime.jsx("div", {
                                            children: "This modal has a custom header component.",
                                            className: "p-4"
                                          }),
                                      primaryButtonText: "Confirm",
                                      secondaryButtonText: "Cancel",
                                      primaryButtonType: "success",
                                      secondaryButtonType: "danger",
                                      customHeader: Caml_option.some(JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx("h3", {
                                                        children: "Custom Header",
                                                        className: "text-lg font-bold text-blue-800"
                                                      }),
                                                  JsxRuntime.jsx(LucideReact.X, {
                                                        size: 20,
                                                        className: "cursor-pointer",
                                                        onClick: (function (param) {
                                                            setIsCustomHeaderModalOpen(function (param) {
                                                                  return false;
                                                                });
                                                          })
                                                      })
                                                ],
                                                className: "p-4 bg-blue-100 flex justify-between items-center"
                                              }))
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Modal with Custom Footer",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "Open Modal with Custom Footer",
                                      className: "px-4 py-2 bg-blue-500 text-white rounded",
                                      onClick: (function (param) {
                                          setIsCustomFooterModalOpen(function (param) {
                                                return true;
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx(DesignSystem.Modal, {
                                      isOpen: match$2[0],
                                      onClose: (function () {
                                          setIsCustomFooterModalOpen(function (param) {
                                                return false;
                                              });
                                        }),
                                      title: "Custom Footer Modal",
                                      children: JsxRuntime.jsx("div", {
                                            children: "This modal has a custom footer with custom buttons.",
                                            className: "p-4"
                                          }),
                                      showPrimaryButton: false,
                                      showSecondaryButton: false,
                                      customFooter: Caml_option.some(JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx("button", {
                                                        children: "Decline",
                                                        className: "px-4 py-2 bg-red-500 text-white rounded",
                                                        onClick: (function (param) {
                                                            setIsCustomFooterModalOpen(function (param) {
                                                                  return false;
                                                                });
                                                          })
                                                      }),
                                                  JsxRuntime.jsx("button", {
                                                        children: "Proceed",
                                                        className: "px-4 py-2 bg-green-500 text-white rounded",
                                                        onClick: (function (param) {
                                                            console.log("Custom action");
                                                            setIsCustomFooterModalOpen(function (param) {
                                                                  return false;
                                                                });
                                                          })
                                                      })
                                                ],
                                                className: "p-4 bg-gray-100 flex justify-end gap-3"
                                              }))
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    })
              ]
            });
}

var ModalDemo = {
  make: ModalDemo$ModalDemo
};

export {
  ModalDemo ,
}
/* react Not a pure module */
