// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function OTPInputDemo$OTPInputDemo(props) {
  var match = React.useState(function () {
        return "";
      });
  var setOtpValue4 = match[1];
  var otpValue4 = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setOtpValue6 = match$1[1];
  var otpValue6 = match$1[0];
  var match$2 = React.useState(function () {
        return "1234";
      });
  var setOtpValueFilled = match$2[1];
  var handleOtp4Change = function (value) {
    setOtpValue4(function (param) {
          return value;
        });
    console.log("4-digit OTP changed: " + value);
  };
  var handleOtp6Change = function (value) {
    setOtpValue6(function (param) {
          return value;
        });
    console.log("6-digit OTP changed: " + value);
  };
  var handleOtpFilledChange = function (value) {
    setOtpValueFilled(function (param) {
          return value;
        });
    console.log("Pre-filled OTP changed: " + value);
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "OTP Input Components",
                      className: "text-2xl font-bold"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Basic 4-Digit OTP Input",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 4,
                                      hintText: "Enter 4-digit code sent to your mobile",
                                      label: "4-Digit OTP",
                                      value: otpValue4,
                                      onChange: handleOtp4Change
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "Current value: " + otpValue4,
                                      className: "text-sm text-gray-600"
                                    })
                              ],
                              className: "space-y-4 max-w-md"
                            })
                      ],
                      className: "border rounded p-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "6-Digit OTP Input",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 6,
                                      hintText: "Enter 6-digit code sent to your email",
                                      label: "6-Digit OTP",
                                      value: otpValue6,
                                      onChange: handleOtp6Change
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "Current value: " + otpValue6,
                                      className: "text-sm text-gray-600"
                                    })
                              ],
                              className: "space-y-4 max-w-md"
                            })
                      ],
                      className: "border rounded p-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "OTP Input States",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 4,
                                      label: "Default State",
                                      state: "default"
                                    }),
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 4,
                                      label: "Hover State",
                                      state: "hover"
                                    }),
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 4,
                                      label: "Focused State",
                                      state: "focused"
                                    }),
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 4,
                                      label: "Filled State",
                                      state: "filled",
                                      value: match$2[0],
                                      onChange: handleOtpFilledChange
                                    }),
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 4,
                                      label: "Error State",
                                      state: "error",
                                      errorMessage: "Invalid OTP code"
                                    }),
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 4,
                                      label: "Success State",
                                      state: "success",
                                      value: "1234",
                                      successMessage: "OTP verified successfully"
                                    }),
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 4,
                                      label: "Disabled State",
                                      state: "disabled"
                                    })
                              ],
                              className: "grid grid-cols-1 md:grid-cols-2 gap-4"
                            })
                      ],
                      className: "border rounded p-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "OTP Input with Labels",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 4,
                                      label: "With Sublabel",
                                      sublabel: "Additional information about this field"
                                    }),
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 4,
                                      hintText: "This is a hint to help you fill this field",
                                      label: "With Hint"
                                    }),
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 4,
                                      label: "Mandatory Field",
                                      mandatory: true
                                    }),
                                JsxRuntime.jsx(DesignSystem.OTPInput, {
                                      digits: 4,
                                      label: "With Info Tooltip",
                                      infoTooltip: "This tooltip provides additional information about the field"
                                    })
                              ],
                              className: "space-y-4 max-w-md"
                            })
                      ],
                      className: "border rounded p-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "OTP Input with Resend Option",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx(DesignSystem.OTPInput, {
                                            digits: 6,
                                            hintText: "Enter the verification code",
                                            label: "OTP Verification",
                                            value: otpValue6,
                                            onChange: handleOtp6Change
                                          }),
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("button", {
                                                    children: "Resend OTP",
                                                    className: "text-blue-500 hover:text-blue-700 text-sm font-medium focus:outline-none",
                                                    onClick: (function (param) {
                                                        console.log("Resending OTP...");
                                                        setOtpValue6(function (param) {
                                                              return "";
                                                            });
                                                      })
                                                  }),
                                              JsxRuntime.jsx("span", {
                                                    children: "•",
                                                    className: "mx-2 text-gray-400"
                                                  }),
                                              JsxRuntime.jsx("span", {
                                                    children: "01:59",
                                                    className: "text-sm text-gray-500"
                                                  })
                                            ],
                                            className: "mt-2 flex items-center"
                                          })
                                    ]
                                  }),
                              className: "space-y-4 max-w-md"
                            })
                      ],
                      className: "border rounded p-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "OTP Input with Custom Styling",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("h3", {
                                            children: "Verify your identity",
                                            className: "text-lg font-medium text-gray-800 mb-2"
                                          }),
                                      JsxRuntime.jsx("p", {
                                            children: "We've sent a 4-digit verification code to +1 (***) ***-7890",
                                            className: "text-sm text-gray-600 mb-4"
                                          }),
                                      JsxRuntime.jsx(DesignSystem.OTPInput, {
                                            digits: 4,
                                            value: otpValue4,
                                            onChange: handleOtp4Change,
                                            className: "mb-4"
                                          }),
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("button", {
                                                    children: "Resend Code",
                                                    className: "text-blue-500 hover:text-blue-700 text-sm font-medium focus:outline-none",
                                                    onClick: (function (param) {
                                                        console.log("Resending OTP...");
                                                        setOtpValue4(function (param) {
                                                              return "";
                                                            });
                                                      })
                                                  }),
                                              JsxRuntime.jsx("button", {
                                                    children: "Verify",
                                                    className: "px-4 py-2 rounded-md text-white font-medium " + (
                                                      otpValue4.length === 4 ? "bg-blue-600 hover:bg-blue-700" : "bg-gray-300 cursor-not-allowed"
                                                    ),
                                                    disabled: otpValue4.length !== 4,
                                                    onClick: (function (param) {
                                                        console.log("Verifying OTP...");
                                                      })
                                                  })
                                            ],
                                            className: "flex justify-between items-center mt-4"
                                          })
                                    ],
                                    className: "bg-gray-50 p-6 rounded-lg"
                                  }),
                              className: "space-y-4 max-w-md"
                            })
                      ],
                      className: "border rounded p-4"
                    })
              ],
              className: "p-4 space-y-8"
            });
}

var OTPInputDemo = {
  make: OTPInputDemo$OTPInputDemo
};

var $$default = OTPInputDemo$OTPInputDemo;

export {
  OTPInputDemo ,
  $$default as default,
}
/* react Not a pure module */
