// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function PopoverDemo(props) {
  var match = React.useState(function () {
        return false;
      });
  var setOpen = match[1];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Popover Demo",
                      className: "text-2xl font-bold mb-6 mt-12"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Basic Popover",
                              className: "text-xl font-semibold"
                            }),
                        JsxRuntime.jsx(DesignSystem.Popover, {
                              children: JsxRuntime.jsx("div", {
                                    children: "This is the popover content",
                                    className: "p-4"
                                  }),
                              trigger: JsxRuntime.jsx("button", {
                                    children: "Click me",
                                    className: "px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
                                  }),
                              placement: "bottom",
                              heading: "Popover Title",
                              description: "This is a basic popover with a title and description.",
                              primaryButtonText: "Confirm",
                              secondaryButtonText: "Cancel",
                              onPrimaryButtonClick: (function () {
                                  console.log("Primary clicked");
                                }),
                              onSecondaryButtonClick: (function () {
                                  console.log("Secondary clicked");
                                })
                            })
                      ],
                      className: "space-y-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Controlled Popover",
                              className: "text-xl font-semibold"
                            }),
                        JsxRuntime.jsx(DesignSystem.Popover, {
                              children: JsxRuntime.jsx("div", {
                                    children: "This is a controlled popover",
                                    className: "p-4"
                                  }),
                              trigger: JsxRuntime.jsx("button", {
                                    children: "Toggle Popover",
                                    className: "px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600",
                                    onClick: (function (param) {
                                        setOpen(function (prev) {
                                              return !prev;
                                            });
                                      })
                                  }),
                              placement: "right",
                              open_: match[0],
                              heading: "Controlled Popover",
                              description: "This popover is controlled by React state.",
                              showCloseButton: true
                            })
                      ],
                      className: "space-y-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Popover with Custom Alignment",
                              className: "text-xl font-semibold"
                            }),
                        JsxRuntime.jsx(DesignSystem.Popover, {
                              children: JsxRuntime.jsx("div", {
                                    children: "This popover is aligned to the end",
                                    className: "p-4"
                                  }),
                              trigger: JsxRuntime.jsx("button", {
                                    children: "Custom Alignment",
                                    className: "px-4 py-2 bg-purple-500 text-white rounded hover:bg-purple-600"
                                  }),
                              placement: "bottom",
                              alignment: "end",
                              heading: "Custom Alignment",
                              description: "This popover has custom alignment settings.",
                              showCloseButton: true
                            })
                      ],
                      className: "space-y-4"
                    })
              ],
              className: "space-y-8"
            });
}

var make = PopoverDemo;

export {
  make ,
}
/* react Not a pure module */
