// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as LucideReact from "lucide-react";
import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function StatCardDemo$StatCardDemo(props) {
  var lineChartData = [
    {
      value: 10.0,
      label: "Jan"
    },
    {
      value: 25.0,
      label: "Feb"
    },
    {
      value: 15.0,
      label: "Mar"
    },
    {
      value: 30.0,
      label: "Apr"
    },
    {
      value: 22.0,
      label: "May"
    },
    {
      value: 40.0,
      label: "Jun"
    }
  ];
  var barChartData = [
    {
      value: 15.0,
      label: "Mon"
    },
    {
      value: 25.0,
      label: "Tue"
    },
    {
      value: 18.0,
      label: "Wed"
    },
    {
      value: 30.0,
      label: "Thu"
    },
    {
      value: 22.0,
      label: "Fri"
    }
  ];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "StatCard Demo",
                      className: "text-2xl font-bold mb-6 mt-12"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Line Variant",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx(DesignSystem.StatCard, {
                                            title: "Revenue",
                                            value: "$12,500",
                                            change: {
                                              value: 12.5,
                                              type_: "increase"
                                            },
                                            subtitle: "Monthly revenue",
                                            variant: "line",
                                            chartData: lineChartData
                                          }),
                                      className: "w-64"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx(DesignSystem.StatCard, {
                                            title: "Users",
                                            value: "1,250",
                                            change: {
                                              value: 5.3,
                                              type_: "decrease"
                                            },
                                            subtitle: "Active users",
                                            variant: "line",
                                            chartData: lineChartData,
                                            titleIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.Users, {
                                                      size: 16
                                                    }))
                                          }),
                                      className: "w-64"
                                    })
                              ],
                              className: "flex flex-wrap gap-4"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Progress Bar Variant",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx(DesignSystem.StatCard, {
                                            title: "Project Completion",
                                            value: "75%",
                                            change: {
                                              value: 15.0,
                                              type_: "increase"
                                            },
                                            subtitle: "3 weeks remaining",
                                            variant: "progress_bar",
                                            progressValue: 75.0,
                                            titleIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.Home, {
                                                      size: 16
                                                    }))
                                          }),
                                      className: "w-64"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx(DesignSystem.StatCard, {
                                            title: "Tasks Completed",
                                            value: "48%",
                                            subtitle: "12 of 25 tasks",
                                            variant: "progress_bar",
                                            progressValue: 48.0,
                                            titleIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.Home, {
                                                      size: 16
                                                    }))
                                          }),
                                      className: "w-64"
                                    })
                              ],
                              className: "flex flex-wrap gap-4"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Bar Variant",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx(DesignSystem.StatCard, {
                                            title: "Weekly Sales",
                                            value: "$8,450",
                                            change: {
                                              value: 23.1,
                                              type_: "increase"
                                            },
                                            subtitle: "This week's sales",
                                            variant: "bar",
                                            chartData: barChartData,
                                            titleIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.BarChart, {
                                                      size: 16
                                                    })),
                                            actionIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.Home, {
                                                      size: 16
                                                    }))
                                          }),
                                      className: "w-64"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx(DesignSystem.StatCard, {
                                            title: "Website Visits",
                                            value: "24,350",
                                            change: {
                                              value: 8.4,
                                              type_: "decrease"
                                            },
                                            subtitle: "Unique visitors",
                                            variant: "bar",
                                            chartData: barChartData,
                                            titleIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.Home, {
                                                      size: 16
                                                    })),
                                            helpIconText: "Total unique website visits in the current period"
                                          }),
                                      className: "w-64"
                                    })
                              ],
                              className: "flex flex-wrap gap-4"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Number Variant",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx(DesignSystem.StatCard, {
                                            title: "Conversions",
                                            value: "3.2%",
                                            change: {
                                              value: 0.8,
                                              type_: "increase"
                                            },
                                            subtitle: "From all visits",
                                            variant: "number",
                                            titleIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.Home, {
                                                      size: 16
                                                    }))
                                          }),
                                      className: "w-64"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx(DesignSystem.StatCard, {
                                            title: "New Customers",
                                            value: "85",
                                            change: {
                                              value: 12.2,
                                              type_: "decrease"
                                            },
                                            subtitle: "This month",
                                            variant: "number",
                                            titleIcon: Caml_option.some(JsxRuntime.jsx(LucideReact.User, {
                                                      size: 16
                                                    }))
                                          }),
                                      className: "w-64"
                                    })
                              ],
                              className: "flex flex-wrap gap-4"
                            })
                      ],
                      className: "mb-8"
                    })
              ]
            });
}

var StatCardDemo = {
  make: StatCardDemo$StatCardDemo
};

export {
  StatCardDemo ,
}
/* lucide-react Not a pure module */
