// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as DesignSystem from "@vinitjuspay/design-system";

function TagDemo$TagDemo(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Tag Variants Demo",
                      className: "text-2xl font-bold mb-6 mt-12"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Tag Variants",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      variant: "noFill",
                                      label: "No Fill"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      variant: "attentive",
                                      label: "Attentive"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      variant: "subtle",
                                      label: "Subtle"
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Tag Styles",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      variant: "attentive",
                                      tagStyle: "rounded",
                                      color: "purple",
                                      label: "Vinit OG"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      tagStyle: "rounded",
                                      label: "Rounded"
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Tag Sizes",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      size: "xs",
                                      label: "Extra Small"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      size: "sm",
                                      label: "Small"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      size: "md",
                                      label: "Medium"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      size: "lg",
                                      label: "Large"
                                    })
                              ],
                              className: "flex flex-wrap items-center gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Tag Colors",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      color: "neutral",
                                      label: "Neutral"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      color: "primary",
                                      label: "Primary"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      color: "success",
                                      label: "Success"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      color: "error",
                                      label: "Error"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      color: "warning",
                                      label: "Warning"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      color: "purple",
                                      label: "Purple"
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Tags with Slots",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      label: "Leading Icon"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      label: "Trailing Icon"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      label: "Both Slots"
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Split Tags",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.SplitTag, {
                                      leftLabel: "Left",
                                      rightLabel: "Right"
                                    }),
                                JsxRuntime.jsx(DesignSystem.SplitTag, {
                                      leftLabel: "With",
                                      rightLabel: "Icons"
                                    }),
                                JsxRuntime.jsx(DesignSystem.SplitTag, {
                                      color: "success",
                                      leftLabel: "Success",
                                      rightLabel: "Tag"
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Combined Variants",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      variant: "attentive",
                                      tagStyle: "rounded",
                                      size: "lg",
                                      color: "success",
                                      label: "Combined"
                                    }),
                                JsxRuntime.jsx(DesignSystem.Tag, {
                                      variant: "subtle",
                                      size: "sm",
                                      color: "error",
                                      label: "Error"
                                    }),
                                JsxRuntime.jsx(DesignSystem.SplitTag, {
                                      tagStyle: "rounded",
                                      size: "md",
                                      color: "primary",
                                      leftLabel: "Split",
                                      rightLabel: "Tag"
                                    })
                              ],
                              className: "flex flex-wrap gap-3"
                            })
                      ],
                      className: "mb-8"
                    })
              ]
            });
}

var TagDemo = {
  make: TagDemo$TagDemo
};

export {
  TagDemo ,
}
/* react/jsx-runtime Not a pure module */
