// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var Ref = {};

var Children = {};

var Context = {};

var Fragment = {};

var StrictMode = {};

var Suspense = {};

function lazy_(load) {
  return React.lazy(async function () {
              return {
                      default: await load()
                    };
            });
}

var Uncurried = {};

export {
  Ref ,
  Children ,
  Context ,
  Fragment ,
  StrictMode ,
  Suspense ,
  lazy_ ,
  Uncurried ,
}
/* react Not a pure module */
